version: '3.8'

services:
  smart-agent:
    image: ghcr.io/ddkang1/smart-agent:latest
    volumes:
      - ./config:/app/config
    depends_on:
      - python-tool
    stdin_open: true
    tty: true

  litellm-proxy:
    image: ghcr.io/berriai/litellm:litellm_stable_release_branch-stable
    volumes:
      - ./config/litellm_config.yaml:/app/config.yaml
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - HOST=0.0.0.0
    command: >
      --config /app/config.yaml
      --port 4000
      --host 0.0.0.0
    profiles:
      - litellm

  python-tool:
    image: ghcr.io/ddkang1/mcp-py-repl:latest
    volumes:
      - ./python_repl_storage:/app/data/
    ports:
      - "8000:8000"
    command: >
      sh -c "npx -y supergateway \
             --port 8000 \
             --stdio 'python -m mcp_py_repl.server' \
             --ssePath /sse \
             --messagePath /message"
